-- MySQL Script generated by MySQL Workbench
-- 11/22/16 08:52:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sir_cyclo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `auth_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_users` ;

CREATE TABLE IF NOT EXISTS `auth_users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '0',
  `first_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `auth_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_roles` ;

CREATE TABLE IF NOT EXISTS `auth_roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_slug_unique` (`slug` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `config_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `config_types` ;

CREATE TABLE IF NOT EXISTS `config_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `configs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `configs` ;

CREATE TABLE IF NOT EXISTS `configs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `type_id` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `type_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_configs_config_types1_idx` (`type_id` ASC),
  CONSTRAINT `fk_configs_config_types1`
    FOREIGN KEY (`type_id`)
    REFERENCES `config_types` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auth_permission_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_permission_types` ;

CREATE TABLE IF NOT EXISTS `auth_permission_types` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auth_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_permissions` ;

CREATE TABLE IF NOT EXISTS `auth_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NULL,
  `role_id` INT(10) UNSIGNED NULL,
  `type_id` INT NOT NULL,
  `permission` VARCHAR(255) NULL,
  `can_access` TINYINT(1) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_permissions_auth_users1_idx` (`user_id` ASC),
  INDEX `fk_permissions_auth_roles1_idx` (`role_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_auth_permissions_permission_types1_idx` (`type_id` ASC),
  CONSTRAINT `fk_permissions_auth_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_permissions_auth_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_roles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_auth_permissions_permission_types1`
    FOREIGN KEY (`type_id`)
    REFERENCES `auth_permission_types` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
