-- MySQL Script generated by MySQL Workbench
-- 09/30/16 10:35:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema slim_auth_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `auth_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_users` ;

CREATE TABLE IF NOT EXISTS `auth_users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `online` TINYINT(1) NOT NULL DEFAULT '0',
  `first_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `auth_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_roles` ;

CREATE TABLE IF NOT EXISTS `auth_roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_slug_unique` (`slug` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `configs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `configs` ;

CREATE TABLE IF NOT EXISTS `configs` (
  `name` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `auth_user_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_user_has_role` ;

CREATE TABLE IF NOT EXISTS `auth_user_has_role` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_auth_users_has_auth_roles_auth_roles1_idx` (`role_id` ASC),
  INDEX `fk_auth_users_has_auth_roles_auth_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_auth_users_has_auth_roles_auth_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_users_has_auth_roles_auth_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `auth_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth_permissions` ;

CREATE TABLE IF NOT EXISTS `auth_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NULL,
  `role_id` INT(10) UNSIGNED NULL,
  `permission` VARCHAR(255) NOT NULL,
  `category` ENUM('role', 'user') NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `allowed` TINYINT(1) NULL,
  INDEX `fk_permissions_auth_users1_idx` (`user_id` ASC),
  INDEX `fk_permissions_auth_roles1_idx` (`role_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_permissions_auth_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissions_auth_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
